###########
# site.title

title:    'mAIncrafters'
subtitle: 'Using AI to Streamline the Crafting Process'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
