'''
File only contains one data structure that holds
    all item recipes required by the minecraft agent
'''

def get_ingredients(item):
    if item not in ITEM_RECIPES:
        return None
    else:
        return ITEM_RECIPES[item]

ITEM_RECIPES = {
    'anvil' : [('iron_ingot', 4), ('iron_block', 3)],
    'armor_stand' : [('smooth_stone_slab', 1), ('stick', 6)],
    'arrow' : [('feather', 1), ('flint', 1), ('stick', 1)],
    'baked_potato' : [],
    'barrel' : [('planks', 6), ('wooden_slabs', 2)],
    'beacon' : [('obsidian', 3), ('nether_star', 1), ('glass', 5)],
    'beehive' : [('honeycomb', 3), ('planks', 6)],
    'beetroot_soup' : [('beetroot', 6), ('bowl', 1)],
    'bone_block' : [('bone_meal', 9)],
    'bone_meal' : [('bone', 1)],
    'book' : [('leather', 1), ('paper', 3)],
    'bookshelf' : [('planks', 6), ('book', 3)],
    'bow' : [('string', 3), ('stick', 3)],
    'bowl' : [('planks', 3)],
    'bread' : [('wheat', 3)],
    'brewing_stand' : [('blaze_rod', 1), ('stone_crafting_materials', 3)],
    'brick' : [],
    'bricks' : [('brick', 4)],
    'brick_slab' : [('bricks', 3)],
    'brick_stairs' : [('bricks', 6)],
    'brick_wall' : [('bricks', 6)],
    'bucket' : [('iron_ingot', 3)],
    'cake' : [('sugar', 2), ('wheat', 3), ('egg', 1), ('milk_bucket', 3)],
    'campfire' : [('coals', 1), ('logs', 3), ('stick', 3)],
    'carrot_on_a_stick' : [('fishing_rod', 1), ('carrot', 1)],
    'cauldron' : [('iron_ingot', 7)],
    'chain' : [('iron_nugget', 2), ('iron_ingot', 1)],
    'charcoal' : [],
    'chest' : [('planks', 8)],
    'chest_minecart' : [('chest', 1), ('minecart', 1)],
    'chiseled_nether_bricks' : [('nether_brick_slab', 2)],
    'chiseled_polished_blackstone' : [('polished_blackstone_slab', 2)],
    'chiseled_quartz_block' : [('quartz_slab', 2)],
    'chiseled_red_sandstone' : [('red_sandstone_slab', 2)],
    'chiseled_sandstone' : [('sandstone_slab', 2)],
    'chiseled_stone_bricks' : [('stone_brick_slab', 2)],
    'clay' : [('clay_ball', 4)],
    'clock' : [('gold_ingot', 4), ('redstone', 1)],
    'coal' : [('coal_block', 1)],
    'coal_block' : [('coal', 9)],
    'coarse_dirt' : [('gravel', 2), ('dirt', 2)],
    'cobblestone_slab' : [('cobblestone', 3)],
    'cobblestone_stairs' : [('cobblestone', 6)],
    'cobblestone_wall' : [('cobblestone', 6)],
    'comparator' : [('redstone_torch', 3), ('quartz', 1), ('stone', 3)],
    'compass' : [('iron_ingot', 4), ('redstone', 1)],
    'composter' : [('wooden_slabs', 7)],
    'conduit' : [('nautilus_shell', 8), ('heart_of_the_sea', 1)],
    'cooked_beef' : [],
    'cooked_chicken' : [],
    'cooked_cod' : [],
    'cooked_mutton' : [],
    'cooked_porkchop' : [],
    'cooked_rabbit' : [],
    'cooked_salmon' : [],
    'cookie' : [('wheat', 2), ('cocoa_beans', 1)],
    'crafting_table' : [('planks', 4)],
    'crossbow' : [('string', 2), ('iron_ingot', 1), ('tripwire_hook', 1), ('stick', 3)],
    'cut_red_sandstone' : [('red_sandstone', 4)],
    'cut_red_sandstone_slab' : [('cut_red_sandstone', 3)],
    'cut_sandstone' : [('sandstone', 4)],
    'cut_sandstone_slab' : [('cut_sandstone', 3)],
    'daylight_detector' : [('quartz', 3), ('wooden_slabs', 3), ('glass', 3)],
    'detector_rail' : [('stone_pressure_plate', 1), ('iron_ingot', 6), ('redstone', 1)],
    'diamond' : [('diamond_ore', 1)],
    'diamond_axe' : [('diamond', 3), ('stick', 2)],
    'diamond_block' : [('diamond', 9)],
    'diamond_boots' : [('diamond', 4)],
    'diamond_chestplate' : [('diamond', 8)],
    'diamond_helmet' : [('diamond', 5)],
    'diamond_hoe' : [('diamond', 2), ('stick', 2)],
    'diamond_leggings' : [('diamond', 7)],
    'diamond_pickaxe' : [('diamond', 3), ('stick', 2)],
    'diamond_shovel' : [('diamond', 1), ('stick', 2)],
    'diamond_sword' : [('diamond', 2), ('stick', 1)],
    'diorite' : [('quartz', 2), ('cobblestone', 2)],
    'diorite_slab' : [('diorite', 3)],
    'diorite_stairs' : [('diorite', 6)],
    'diorite_wall' : [('diorite', 6)],
    'dispenser' : [('cobblestone', 7), ('bow', 1), ('redstone', 1)],
    'dried_kelp' : [('dried_kelp_block', 1)],
    'dried_kelp_block' : [('dried_kelp', 9)],
    'dropper' : [('cobblestone', 7), ('redstone', 1)],
    'emerald' : [('emerald_block', 1)],
    'emerald_block' : [('emerald', 9)],
    'enchanting_table' : [('obsidian', 4), ('book', 1), ('diamond', 2)],
    'ender_chest' : [('obsidian', 8), ('ender_eye', 1)],
    'ender_eye' : [('blaze_powder', 1), ('ender_pearl', 1)],
    'end_crystal' : [('glass', 7), ('ghast_tear', 1), ('ender_eye', 1)],
    'end_rod' : [('popped_chorus_fruit', 1), ('blaze_rod', 1)],
    'end_stone_bricks' : [('end_stone', 4)],
    'end_stone_brick_slab' : [('end_stone_bricks', 3)],
    'end_stone_brick_stairs' : [('end_stone_bricks', 6)],
    'end_stone_brick_wall' : [('end_stone_bricks', 6)],
    'fermented_spider_eye' : [('sugar', 1), ('spider_eye', 1), ('brown_mushroom', 1)],
    'fire_charge' : [('blaze_powder', 1), ('charcoal', 1), ('gunpowder', 1), ('coal', 1)],
    'fishing_rod' : [('string', 2), ('stick', 3)],
    'flint_and_steel' : [('flint', 1), ('iron_ingot', 1)],
    'flower_pot' : [('brick', 3)],
    'furnace' : [('stone_crafting_materials', 8)],
    'furnace_minecart' : [('furnace', 1), ('minecart', 1)],
    'glass' : [],
    'glass_bottle' : [('glass', 3)],
    'glass_pane' : [('glass', 6)],
    'glistering_melon_slice' : [('gold_nugget', 8), ('melon_slice', 1)],
    'glowstone' : [('glowstone_dust', 4)],
    'golden_apple' : [('gold_ingot', 8), ('apple', 1)],
    'golden_axe' : [('gold_ingot', 3), ('stick', 2)],
    'golden_boots' : [('gold_ingot', 4)],
    'golden_carrot' : [('gold_nugget', 8), ('carrot', 1)],
    'golden_chestplate' : [('gold_ingot', 8)],
    'golden_helmet' : [('gold_ingot', 5)],
    'golden_hoe' : [('gold_ingot', 2), ('stick', 2)],
    'golden_leggings' : [('gold_ingot', 7)],
    'golden_pickaxe' : [('gold_ingot', 3), ('stick', 2)],
    'golden_shovel' : [('gold_ingot', 1), ('stick', 2)],
    'golden_sword' : [('gold_ingot', 2), ('stick', 1)],
    'gold_block' : [('gold_ingot', 9)],
    'gold_ingot' : [('gold_ore',1)],
    'gold_nugget' : [('gold_ingot', 1)],
    'grindstone' : [('planks', 2), ('stone_slab', 1), ('stick', 2)],
    'hay_block' : [('wheat', 9)],
    'heavy_weighted_pressure_plate' : [('iron_ingot', 2)],
    'honeycomb_block' : [('honeycomb', 4)],
    'honey_block' : [('honey_bottle', 4)],
    'honey_bottle' : [('glass_bottle', 4), ('honey_block', 1)],
    'hopper' : [('chest', 1), ('iron_ingot', 5)],
    'hopper_minecart' : [('minecart', 1), ('hopper', 1)],
    'iron_axe' : [('iron_ingot', 3), ('stick', 2)],
    'iron_bars' : [('iron_ingot', 6)],
    'iron_block' : [('iron_ingot', 9)],
    'iron_boots' : [('iron_ingot', 4)],
    'iron_chestplate' : [('iron_ingot', 8)],
    'iron_door' : [('iron_ingot', 6)],
    'iron_helmet' : [('iron_ingot', 5)],
    'iron_hoe' : [('iron_ingot', 2), ('stick', 2)],
    'iron_ingot' : [('iron_ore',1)],
    'iron_leggings' : [('iron_ingot', 7)],
    'iron_nugget' : [('iron_ingot', 1)],
    'iron_pickaxe' : [('iron_ingot', 3), ('stick', 2)],
    'iron_shovel' : [('iron_ingot', 1), ('stick', 2)],
    'iron_sword' : [('iron_ingot', 2), ('stick', 1)],
    'iron_trapdoor' : [('iron_ingot', 4)],
    'item_frame' : [('leather', 1), ('stick', 8)],
    'jack_o_lantern' : [('carved_pumpkin', 1), ('torch', 1)],
    'jukebox' : [('planks', 8), ('diamond', 1)],
    'ladder' : [('stick', 7)],
    'lantern' : [('iron_nugget', 8), ('torch', 1)],
    'lapis_block' : [('lapis_lazuli', 9)],
    'lapis_lazuli' : [],
    'lead' : [('slime_ball', 1), ('string', 4)],
    'leather' : [('rabbit_hide', 4)],
    'leather_boots' : [('leather', 4)],
    'leather_chestplate' : [('leather', 8)],
    'leather_helmet' : [('leather', 5)],
    'leather_horse_armor' : [('leather', 7)],
    'leather_leggings' : [('leather', 7)],
    'lectern' : [('wooden_slabs', 4), ('bookshelf', 1)],
    'lever' : [('cobblestone', 1), ('stick', 1)],
    'light_weighted_pressure_plate' : [('gold_ingot', 2)],
    'lodestone' : [('netherite_ingot', 1), ('chiseled_stone_bricks', 8)],
    'loom' : [('planks', 2), ('string', 2)],
    'magma_block' : [('magma_cream', 4)],
    'magma_cream' : [('blaze_powder', 1), ('slime_ball', 1)],
    'map' : [('compass', 1), ('paper', 8)],
    'melon' : [('melon_slice', 9)],
    'melon_seeds' : [('melon_slice', 1)],
    'minecart' : [('iron_ingot', 5)],
    'mojang_banner_pattern' : [('enchanted_golden_apple', 1), ('paper', 1)],
    'mossy_cobblestone' : [('vine', 1), ('cobblestone', 1)],
    'mossy_cobblestone_slab' : [('mossy_cobblestone', 3)],
    'mossy_cobblestone_stairs' : [('mossy_cobblestone', 6)],
    'mossy_cobblestone_wall' : [('mossy_cobblestone', 6)],
    'mossy_stone_bricks' : [('stone_bricks', 1), ('vine', 1)],
    'mossy_stone_brick_slab' : [('mossy_stone_bricks', 3)],
    'mossy_stone_brick_stairs' : [('mossy_stone_bricks', 6)],
    'mossy_stone_brick_wall' : [('mossy_stone_bricks', 6)],
    'mushroom_stew' : [('red_mushroom', 1), ('brown_mushroom', 1), ('bowl', 1)],
    'nether_brick' : [],
    'nether_bricks' : [('nether_brick', 4)],
    'nether_brick_fence' : [('nether_bricks', 4), ('nether_brick', 2)],
    'nether_brick_slab' : [('nether_bricks', 3)],
    'nether_brick_stairs' : [('nether_bricks', 6)],
    'nether_brick_wall' : [('nether_bricks', 6)],
    'nether_wart_block' : [('nether_wart', 9)],
    'note_block' : [('planks', 8), ('redstone', 1)],
    'packed_ice' : [('ice', 9)],
    'painting' : [('wool', 1), ('stick', 8)],
    'paper' : [('sugar_cane', 3)],
    'piston' : [('planks', 3), ('cobblestone', 4), ('iron_ingot', 1), ('redstone', 1)],
    'planks' : [('log', 1)],
    'stick' : [('planks', 2)],
    'stone_pickaxe' : [('cobblestone', 3), ('stick', 2)],
}
